var wordTypes = {
	"CC": "Coord Conjuncn",
	"PSP": "Postjunction",
	"CD": "Cardinal number",
	"DT": "Determiner",
	"EX": "Existential there",
	"FW": "Foreign Word",
	"IN": "Preposition",
	"JJ": "Adjective",
	"JJR": "Adj., comparative",
	"JJS": "Adj., superlative",
	"LS": "List item marker",
	"MD": "Modal",
	"NN": "Noun, sing. or mass",
	"N_NN":"Noun, sing. or mass",
	"NNP": "Proper noun, sing.",
	"N_NST": "Spatio-temporal",
	"N_NNP": "Proper noun, sing.",
	"NNPS": "Proper noun, plural",
	"NNS": "Noun, plural",
	"N_NNV":"Verbal Noun",
	"POS": "Possessive ending",
	"PDT": "Predeterminer",
	"PP$": "Possessive pronoun",
	"PRP": "Personal pronoun",
	"PR_PRP": "Personal pronoun",
	"PR_PRL": "Relative pronoun",
	"PR_PRF": "Reflexive Pronoun",
	"PR_PRC": "Reciprocal Pronoun",
	"RB": "Adverb",
	"RBR": "Adverb, comparative",
	"RBS": "Adverb, superlative",
	"RP": "Particle",
	"RP_RPD": "Default Particle",
	"RP_NEG": "Negation Particle",
	"RP_INTF": "Intensifier Particle",
	"RP_INJ": "Interjection Particle",
	"RD_RDF": "Foreign Words",
	"RB_ALC": "Adverb of Locations",
	"RB_AMN": "Adverb of Manners",
	"RD_SYM": "Symbol",
	"RP_UNK": "Unknown",
	"SYM": "Symbol",
	"DM_DMD": "Indefinite Demonstratives",
	"DM_DMI": "Absolute Demonstratives",
	"DM_DMQ": "wH-word Demonstratives",
	"DM_DMR": "Relative Demonstratives",
	"TO": "to",
	"UH": "Interjection",
	"URL": "url",
	"VB": "verb, base form",
	"V_VM":"verb, base form",
	"V_VAUX":"auxiliary verb",
	"VBD": "verb, past tense",
	"VBG": "verb, gerund",
	"VBN": "verb, past part",
	"VBP": "Verb, present",
	"VBZ": "Verb, present",
	"WDT": "Wh-determiner",
	"WP": "Wh pronoun",
	"WP$": "Possessive-Wh",
	"WRB": "Wh-adverb",
	"RD_PUNC": "Punctuations",
	"QT_QTF": "General Quantifier",
	"QT_QTC": "General Cardinals",
	"QT_QTO": "General Ordinal",
	",": "Comma",
	".": "Sent-final punct",
	":": "Mid-sent punct.",
	"$": "Dollar sign",
	"#": "Pound sign",
	"\"": "quote",
	"(": "Left paren",
	")": "Right paren"
};
